In [1]:
import numpy as np
import os
import cv2
import matplotlib.pyplot as plt
from PIL import Image
import pandas as pd

In [2]:
dataset=pd.read_csv(r'C:\\Users\\pllab\\git\\x_ray pnemonia\\archive\\Chest_xray_Corona_Metadata.csv')

In [3]:
dataset=np.array(dataset)

In [4]:
b=0
for i in range(len(dataset)):
    if not dataset[i][3]=='TRAIN':
            b=dataset[i][0]
            break

In [5]:
b

5286

In [6]:
trainlabel,testlabel=np.split(dataset,[5286],axis=0)

In [7]:
trainlabel

array([[0, 'IM-0128-0001.jpeg', 'Normal', 'TRAIN', nan, nan],
       [1, 'IM-0127-0001.jpeg', 'Normal', 'TRAIN', nan, nan],
       [2, 'IM-0125-0001.jpeg', 'Normal', 'TRAIN', nan, nan],
       ...,
       [5283, '1-s2.0-S0929664620300449-gr2_lrg-a.jpg', 'Pnemonia',
        'TRAIN', 'COVID-19', 'Virus'],
       [5284, '1-s2.0-S0140673620303706-fx1_lrg.jpg', 'Pnemonia',
        'TRAIN', 'COVID-19', 'Virus'],
       [5285, '01E392EE-69F9-4E33-BFCE-E5C968654078.jpeg', 'Pnemonia',
        'TRAIN', 'COVID-19', 'Virus']], dtype=object)

In [8]:
testlabel

array([[5286, 'IM-0021-0001.jpeg', 'Normal', 'TEST', nan, nan],
       [5287, 'IM-0019-0001.jpeg', 'Normal', 'TEST', nan, nan],
       [5288, 'IM-0017-0001.jpeg', 'Normal', 'TEST', nan, nan],
       ...,
       [5907, 'person1634_virus_2830.jpeg', 'Pnemonia', 'TEST', nan,
        'Virus'],
       [5908, 'person1633_virus_2829.jpeg', 'Pnemonia', 'TEST', nan,
        'Virus'],
       [5909, 'person1632_virus_2827.jpeg', 'Pnemonia', 'TEST', nan,
        'Virus']], dtype=object)

In [9]:
anslabel=trainlabel[:,2:]


In [10]:
anslabel[5284]

array(['Pnemonia', 'TRAIN', 'COVID-19', 'Virus'], dtype=object)

In [11]:
trainlabel

array([[0, 'IM-0128-0001.jpeg', 'Normal', 'TRAIN', nan, nan],
       [1, 'IM-0127-0001.jpeg', 'Normal', 'TRAIN', nan, nan],
       [2, 'IM-0125-0001.jpeg', 'Normal', 'TRAIN', nan, nan],
       ...,
       [5283, '1-s2.0-S0929664620300449-gr2_lrg-a.jpg', 'Pnemonia',
        'TRAIN', 'COVID-19', 'Virus'],
       [5284, '1-s2.0-S0140673620303706-fx1_lrg.jpg', 'Pnemonia',
        'TRAIN', 'COVID-19', 'Virus'],
       [5285, '01E392EE-69F9-4E33-BFCE-E5C968654078.jpeg', 'Pnemonia',
        'TRAIN', 'COVID-19', 'Virus']], dtype=object)

In [12]:
rows,cols= anslabel.shape[:2]

In [13]:
rows

5286

In [14]:
cols

4

In [15]:
train_label=[]
total_train_label=[]
for row in range(rows):
    for col in range(cols): 
        if anslabel[row][0]=='Normal': 
            train_label=[1,0,0,0,0,0,0]
        elif anslabel[row][0]=='Pnemonia' and anslabel[row][2]=='nan' and anslabel[row][3]=='Virus': 
            train_label=[0,1,0,0,0,0,0]
        elif anslabel[row][0]=='Pnemonia' and anslabel[row][2]=='nan' and anslabel[row][3]=='bacteria':
            train_label=[0,0,1,0,0,0,0]
        elif anslabel[row][0]=='Pnemonia' and anslabel[row][2]=='Streptococcus' and anslabel[row][3]=='bacteria': 
            train_label=[0,0,0,1,0,0,0]
        elif anslabel[row][0]=='Pnemonia' and anslabel[row][2]==anslabel[row][2]=='COVID-19' and anslabel[row][3]=='Virus': 
            train_label=[0,0,0,0,1,0,0]
      
        elif anslabel[row][0]=='Pnemonia' and anslabel[row][2]==anslabel[row][2]=='ARDS' and anslabel[row][3]=='Stress-Smoking': 
            train_label=[0,0,0,0,0,1,0]
        elif anslabel[row][0]=='Pnemonia' and anslabel[row][2]==anslabel[row][2]=='SARS' and anslabel[row][3]=='Virus': 
            train_label=[0,0,0,0,0,0,1]
    total_train_label.append(train_label)

In [16]:
total_train_label=np.array(total_train_label)

In [17]:
trainlabel=np.array(trainlabel)

In [18]:
rows=trainlabel.shape[:1]

In [19]:
total_train_label.shape

(5286, 7)

In [20]:
x_train=[]

for i in range(rows[0]):
    img_dir=trainlabel[i][1]
    x_train.append(np.array(Image.open('C:\\Users\\pllab\\git\\x_ray pnemonia\\archive\\Coronahack_Chest_XRay_Dataset\\Coronahack_Chest-XRay_Dataset\\train\\'+img_dir)))
    

In [21]:
x_train=np.array(x_train)

In [22]:
np.random.seed(1)

In [23]:
total_train_label[1][0]

1

In [24]:
from tensorflow.keras.models import Sequential

In [25]:
x_train.shape

(5286, 200, 200, 3)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_train2,total_train_label,total_train_label2=train_test_split(x_train,total_train_label,test_size=0.3,random_state=42)

In [28]:
total_train_label[0]

array([1, 0, 0, 0, 0, 0, 0])

In [29]:
x_train.shape

(3700, 200, 200, 3)

In [30]:
total_train_label.shape

(3700, 7)

In [31]:
x_train.shape

(3700, 200, 200, 3)

In [32]:

from tensorflow.keras.optimizers import Adam

In [33]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D,MaxPooling2D,GlobalAveragePooling2D,Dense,Dropout
from tensorflow.keras.layers import Input


In [34]:
inputs=Input(shape=(200,200,3))
x=Conv2D(32,(3,3),activation='relu')(inputs)
x=Conv2D(32,(3,3),activation='relu')(x)
x=MaxPooling2D(strides=2)(x)
x=Dropout(0.2)(x)
x=Conv2D(64,(3,3),activation='relu')(x)
x=Conv2D(64,(3,3),activation='relu')(x)
x=MaxPooling2D(strides=2)(x)
x=Dropout(0.2)(x)
x=Conv2D(128,(3,3),activation='relu')(x)
x=Conv2D(128,(3,3),activation='relu')(x)
x=MaxPooling2D(strides=2)(x)
x=Dropout(0.2)(x)


x=GlobalAveragePooling2D()(x)

x=Dense(7,activation='softmax')(x)

model=Model(inputs=inputs,outputs=x)

In [35]:
model.compile(optimizer=Adam(1e-4),
             loss='categorical_crossentropy',
             metrics=['acc'])

In [ ]:
model.fit(x_train,total_train_label,
         epochs=15,
         batch_size=32,
         validation_data=(x_train2,total_train_label2))

Epoch 1/15
116/116 [==============================] - 35s 264ms/step - loss: 0.8490 - acc: 0.9199 - val_loss: 0.3519 - val_acc: 0.9887
Epoch 2/15
116/116 [==============================] - 26s 222ms/step - loss: 0.1055 - acc: 0.9847 - val_loss: 0.3692 - val_acc: 0.9887
Epoch 3/15
116/116 [==============================] - 26s 221ms/step - loss: 0.0733 - acc: 0.9898 - val_loss: 0.5105 - val_acc: 0.9887
Epoch 4/15
  4/116 [>.............................] - ETA: 21s - loss: 0.0370 - acc: 0.9961